sources:
  - name: reddit_massive_date_questions
    type: html
    url: "https://www.reddit.com/r/dating_advice/comments/hcq28r/massive_list_of_date_questions_and_conversation/"
    category_hint: dating
    explicit_allowed: true

  - name: esther_perel_sexuality_pdf
    type: pdf
    url: "https://static1.squarespace.com/static/54c24381e4b01ce51167623a/t/5915159a46c3c4bb47744a39/1494554010875/Esther+Perel+Sex+Conversation+Starters.pdf"
    category_hint: sexual
    explicit_allowed: true

  - name: winshape_280_couples
    type: html
    url: "https://marriage.winshape.org/resource/conversation-starters-for-date-night/"
    category_hint: romantic
    explicit_allowed: false

  - name: berkeley_36_questions
    type: html
    url: "https://ggia.berkeley.edu/practice/36_questions_for_increasing_closeness"
    category_hint: intimacy
    explicit_allowed: false
