sources:
  - name: fitness_dating_csv
    type: csv
    path: "data/raw/fitness_dating.csv"
    category_hint: "fitness" # This will be used as a fallback
    explicit_allowed: false
  - name: csw_250_starters
    type: html
    url: "https://conversationstartersworld.com/250-conversation-starters/"
    category_hint: "dating"
    explicit_allowed: false
  - name: csw_get_to_know
    type: html
    url: "https://conversationstartersworld.com/questions-to-get-to-know-someone/"
    category_hint: "intimacy"
    explicit_allowed: false
  - name: csw_deep_topics
    type: html
    url: "https://conversationstartersworld.com/deep-conversation-topics/"
    category_hint: "deep"
    explicit_allowed: false
  - name: csw_fun_questions
    type: html
    url: "https://conversationstartersworld.com/fun-questions-to-ask/"
    category_hint: "playful"
    explicit_allowed: false
  - name: csw_first_date
    type: html
    url: "https://conversationstartersworld.com/first-date-questions/"
    category_hint: "dating"
    explicit_allowed: false
  - name: csw_for_couples
    type: html
    url: "https://conversationstartersworld.com/questions-for-couples/"
    category_hint: "romantic"
    explicit_allowed: true
  - name: csw_philosophical
    type: html
    url: "https://conversationstartersworld.com/philosophical-questions/"
    category_hint: "deep"
    explicit_allowed: false
  - name: csw_hypothetical
    type: html
    url: "https://conversationstartersworld.com/hypothetical-questions/"
    category_hint: "playful"
    explicit_allowed: false
